apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlag
metadata:
  name: app-flags-operator
spec:
  flagSpec:
    flags:
      nova-funcao:
        state: "ENABLED"
        variants:
          "on": true
          "off": false
        defaultVariant: "off"
      welcome-message:
        state: "ENABLED"
        variants:
          "v1": "Bem-vindo ao nosso serviço (modo operator)!"
          "v2": "Olá! Parece que estamos enfrentando alguns problemas (modo operator). Nossa equipe está trabalhando nisso!"
        defaultVariant: "v1"
---
apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlagSource
metadata:
  name: feature-flag-source-operator
spec:
  sources:
  - source: default/app-flags-operator
    provider: kubernetes
  port: 8013
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app-operator
spec:
  selector:
    matchLabels:
      app: hello-world-operator
  template:
    metadata:
      labels:
        app: hello-world-operator
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3000"
        openfeature.dev/enabled: "true"
        openfeature.dev/featureflagsource: "default/feature-flag-source-operator"
    spec:
      containers:
      - name: hello-world
        image: hello-world-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: FLAGD_MODE
          value: "operator"
        - name: FLAGD_HOST
          value: "localhost"
        - name: FLAGD_PORT
          value: "8013"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service-operator
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "3000"
spec:
  selector:
    app: hello-world-operator
  ports:
  - port: 80
    targetPort: 3000
