# flagd.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagd
spec:
  selector:
    matchLabels:
      app: flagd
  template:
    metadata:
      labels:
        app: flagd
    spec:
      containers:
      - name: flagd
        image: ghcr.io/open-feature/flagd:latest
        args:
        - start
        - --uri
        - http://prometheus-provider:8017/flags.yaml
        - --port
        - "8013"
        - --management-port
        - "8014"
        ports:
        - name: http
          containerPort: 8013
        - name: management
          containerPort: 8014
---
apiVersion: v1
kind: Service
metadata:
  name: flagd
spec:
  selector:
    app: flagd
  ports:
  - name: http
    port: 8013
    targetPort: http
  - name: management
    port: 8014
    targetPort: management