apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-flags
data:
  flags.yaml: |
    flags:
      nova-funcao:
        state: ENABLED
        variants:
          on: true
          off: false
        defaultVariant: "on"