apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
spec:
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3000"
    spec:
      containers:
      - name: hello-world
        image: hello-world-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: FLAGD_HOST
          value: "flagd"
        - name: FLAGD_PORT
          value: "8013"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "3000"
spec:
  selector:
    app: hello-world
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hello-world-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-world-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
