version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.dev
    command: npx nx serve frontend --host 0.0.0.0
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.dev
    command: npx nx serve backend --host 0.0.0.0
    ports:
      - "3000:3000"
      - "9229:9229" # Debug port
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network

volumes:
  node_modules:

networks:
  app-network:
    driver: bridge
