apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics" 
    spec:
      containers:
      - name: hello-world
        image: hello-world-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: metrics 
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: hello-world
  ports:
  - port: 80
    targetPort: 3000
    name: web
  - port: 3000
    targetPort: 3000
    name: metrics
  type: ClusterIP